#!/bin/bash

set -euo pipefail

PASSPHRASE_FILE=./passphrase.txt

gum input --password --placeholder="Enter Password" > $PASSPHRASE_FILE

gpg --batch --passphrase-file $PASSPHRASE_FILE -d secret.tar.gz.gpg \
  | tar -xvzf -

rm ./passphrase.txt
