#!/bin/bash

set -euo pipefail

PASSPHRASE_FILE=./passphrase.txt

gum input --password --placeholder="Enter Password" > $PASSPHRASE_FILE

tar -cvzf - ./secret/ \
  | gpg --batch --passphrase-file $PASSPHRASE_FILE -c  > ./secret.tar.gz.gpg

rm $PASSPHRASE_FILE
