#!/bin/sh

if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if test ! $(which rustup); then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

if test ! -s ~/.config/fish/functions/fisher.fish; then
  echo "asdf"
  curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fi

brew update
brew bundle --file $PWD/homebrew/Brewfile
