#!/bin/bash

symlink() {
  TARGET=$(readlink $2)
  if [ "$TARGET" != "$1" ]; then
    ln -sn $1 $2
  fi
}

# Setup symlinks
mkdir -p $HOME/.config
symlink $PWD/nvim $HOME/.config/nvim
symlink $PWD/alacritty $HOME/.config/alacritty
symlink $PWD/tmux/tmux.conf $HOME/.tmux.conf
symlink $PWD/git/gitconfig $HOME/.gitconfig
symlink $PWD/git/gitignore $HOME/.gitignore
symlink $PWD/scripts $HOME/scripts
symlink $PWD/fish/config.fish $HOME/.config/fish/config.fish
