#!/bin/sh

if ! test $ZSH ; then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
fi

if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if test ! $(which rustup); then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

brew update
brew bundle --file $PWD/homebrew/Brewfile
