#!/bin/bash

set -euo pipefail

# symlink <original> <link>
symlink() {
  OG=$(readlink -f $1)
  if [ "$OG" != "$(readlink -f $2)" ]; then
    ln -snT $OG $2
  fi
}

DIRNAME="$( dirname -- "${BASH_SOURCE[0]}" )"
pushd $DIRNAME > /dev/null

# Setup symlinks
mkdir -p $HOME/.config
symlink ./nvim $HOME/.config/nvim
symlink ./tmux/tmux.conf $HOME/.tmux.conf
symlink ./git/gitconfig $HOME/.gitconfig
symlink ./git/gitignore $HOME/.gitignore
symlink ./scripts $HOME/scripts
symlink ./fish $HOME/.config/fish
symlink ./ssh/rc $HOME/.ssh/rc
symlink ./alacritty $HOME/.config/alacritty

popd > /dev/null
