# tools
brew "bat"
brew "direnv"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "tree"
brew "gawk"
brew "git-delta"

# languages
brew "deno"
brew "zig"
brew "gcc"
brew "go"

# programs
brew "nethack"
brew "neovim"
brew "git"
brew "tmux"
brew "tldr"
brew "pandoc"
brew "docker-compose"

# misc
brew "cloudflare/cloudflare/cloudflared"
brew "gh"
brew "pinentry-mac"

# casks
cask "alacritty"
cask "basictex"
cask "docker"
