# core
brew "ripgrep"
brew "neovim"
brew "git"
brew "tmux"
brew "fish"
brew "jq"
brew "rsync"
brew "gnupg"

# glitter
brew "bat"
brew "gum"
brew "gh"
brew "tldr"
# brew "pandoc"

# gamer
brew "nethack"
