#!/usr/bin/python3
from typing import Dict, List
from random import shuffle
from sys import argv

cards: Dict[str, List] = {}

def load_cards(): 
    topic = "NONE"
    subtopic = "NONE"

    file = open(argv[1], "r")

    for raw_line in file:
        line = raw_line.rstrip("\n")
        if line.startswith("---"):
            subtopic = "NONE"
        elif line.startswith("# "):
            topic = line[2:]
            subtopic = "NONE"
        elif line.startswith("## "):
            subtopic = f"[{topic}] {line[3:]}"
            cards[subtopic] = []
        elif subtopic != "NONE":
            cards[subtopic].append(line)

def show_card(index: int):
    key = list(cards.keys())[index]
    print(key)
    input()
    for line in cards[key]:
        print(line)

order = list(range(len(cards)))
shuffle(order)
for index in order:
    show_card(index)
