#!/usr/bin/python3
from typing import Dict, List
from random import shuffle
from sys import argv


def load_cards(): 
    cards: Dict[str, List] = {}
    topic = "NONE"
    subtopic = "NONE"

    file = open(argv[1], "r")

    for raw_line in file:
        line = raw_line.rstrip("\n")
        if line.startswith("---"):
            subtopic = "NONE"
        elif line.startswith("# "):
            topic = line[2:]
            subtopic = "NONE"
        elif line.startswith("## "):
            subtopic = f"[{topic}] {line[3:]}"
            cards[subtopic] = []
        elif subtopic != "NONE":
            cards[subtopic].append(line)
    return cards

def show_card(cards, index):
    key = list(cards.keys())[index]
    print(key)
    input()
    for line in cards[key]:
        print(line)

cards = load_cards()
order = list(range(len(cards)))
shuffle(order)
for index in order:
    show_card(cards, index)
