#!/bin/bash

project_status() {
  cd ~/projects/$1;
  if [ ! -e '.git' ]; then
    echo "? $1" # no git repo
  else
    if [ "$(git status -s 2>/dev/null)" ]; then # dirty
      echo "✗ $1"
    else
      if [ "$(git branch -r 2>/dev/null)" ]; then # remotes exist
        if [[ $(git status -sb 2>/dev/null) == *"ahead"* ]]; then # ahead
          echo "↑ $1"
        else
          echo "  $1" # all pushed
        fi
      else
          echo "? $1" # no remote
      fi
    fi
  fi
}

export -f project_status
ls ~/projects | xargs -n 1 bash -c 'project_status "$0"'
