# omz
export ZSH="/Users/will/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git autojump)
source $ZSH/oh-my-zsh.sh

# my stuff
alias cat=bat

# idk what this is for
autoload -U compinit; compinit

# direnv
eval "$(direnv hook zsh)"

# gcloud
if [ -f '/Users/will/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/will/bin/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/will/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/will/bin/google-cloud-sdk/completion.zsh.inc'; fi
